"""Update user table is_active

Revision ID: 11d889e93729
Revises: 654a9f9bb643
Create Date: 2025-12-04 12:43:53.750905

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "11d889e93729"
down_revision: Union[str, Sequence[str], None] = "654a9f9bb643"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Add column as nullable with server default
    op.add_column(
        "users",
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default="true",
            nullable=True,
        ),
    )

    # 2. Backfill existing rows (avoid NULL issues)
    op.execute("UPDATE users SET is_active = true WHERE is_active IS NULL")

    # 3. Set NOT NULL constraint now that rows are filled
    op.alter_column("users", "is_active", nullable=False, server_default="true")

    # 4. Create index
    op.create_index(op.f("ix_users_is_active"), "users", ["is_active"], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_is_active"), table_name="users")
    op.drop_column("users", "is_active")
    # ### end Alembic commands ###
