"""added email_verify_token,is_verified to users table

Revision ID: 5a2d204177f9
Revises: 11d889e93729
Create Date: 2025-12-04 16:51:38.892755

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5a2d204177f9"
down_revision: Union[str, Sequence[str], None] = "11d889e93729"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "is_verified", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    op.add_column(
        "users", sa.Column("email_verify_token", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "email_verify_token")
    op.drop_column("users", "is_verified")
    # ### end Alembic commands ###
